# Generated by Django 4.0.4 on 2022-04-28 10:41

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user-profiles/')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('user_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('doctor_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('more_info', models.TextField(blank=True, null=True)),
                ('doc_stat', models.CharField(choices=[('re', 'requested'), ('dr', 'didnt_requested'), ('ac', 'accepted'), ('de', 'rejected')], default='dr', max_length=2)),
                ('user_status', models.CharField(choices=[('pa', 'patient'), ('su', 'superuser'), ('ad', 'admin'), ('do', 'doctor')], default='pa', max_length=2)),
                ('add_hospital', models.BooleanField(default=False)),
                ('add_doctor', models.BooleanField(default=False)),
                ('add_admin', models.BooleanField(default=False)),
                ('current_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
