# Generated by Django 4.0.4 on 2022-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='current_hospital',
            new_name='hospital_to_request',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='doc_stat',
            field=models.CharField(choices=[('re', 'requested'), ('dr', 'didnt_requested'), ('ac', 'accepted'), ('de', 'declined')], default='dr', max_length=2),
        ),
    ]
