# Generated by Django 4.0.4 on 2022-04-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_current_hospital_baseuser_hospital_to_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='doc_stat',
            field=models.CharField(blank=True, choices=[('re', 'requested'), ('dr', 'didnt_requested'), ('ac', 'accepted'), ('de', 'declined')], default='dr', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='user_status',
            field=models.CharField(blank=True, choices=[('pa', 'patient'), ('su', 'superuser'), ('ad', 'admin'), ('do', 'doctor')], default='pa', max_length=2, null=True),
        ),
    ]
