# Generated by Django 4.0.4 on 2022-04-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_baseuser_doc_stat_alter_baseuser_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='admin_stat',
            field=models.CharField(blank=True, choices=[('re', 'requested'), ('dr', 'didnt_requested'), ('ac', 'accepted'), ('de', 'declined')], default='dr', max_length=2, null=True),
        ),
    ]
