# Generated by Django 4.0.4 on 2022-05-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_hospital_status'),
        ('base', '0005_baseuser_admin_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='hospital_to_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
