# Generated by Django 3.2.13 on 2022-05-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_message_token'),
        ('base', '0007_admin_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_to_request',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital_to_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
