# Generated by Django 3.2.13 on 2022-05-22 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220522_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='add_admin',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='add_doctor',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='add_hospital',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='admin_description',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='admin_stat',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='doc_stat',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='hospital_to_request',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='more_info',
        ),
    ]
