# Generated by Django 3.2.13 on 2022-05-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220522_1801'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
