# Generated by Django 3.2.13 on 2022-05-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
