# Generated by Django 4.0.4 on 2022-08-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_baseuser_email_alter_baseuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='baseuser',
            managers=[
            ],
        ),
    ]
