# Generated by Django 4.0.4 on 2022-08-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_baseuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='username',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
    ]
