# Generated by Django 4.0.4 on 2022-08-04 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_baseuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='username',
        ),
    ]
