# Generated by Django 3.2.13 on 2022-05-22 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_stat', models.CharField(blank=True, choices=[('re', 'requested'), ('dr', 'didnt_requested'), ('ac', 'accepted'), ('de', 'declined')], default='dr', max_length=2, null=True)),
                ('admin_description', models.TextField(blank=True, null=True)),
                ('applier', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_applier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
