# Generated by Django 4.0.4 on 2022-04-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=80)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='hospital_picture/')),
                ('hospital_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('a', 'accepted'), ('r', 'rejected'), ('n', 'no_answer')], default='n', max_length=2)),
                ('description', models.TextField()),
            ],
        ),
    ]
