# Generated by Django 4.0.4 on 2022-04-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_hospital_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'accepted'), ('r', 'rejected'), ('n', 'no_answer')], default='n', max_length=2, null=True),
        ),
    ]
