# Generated by Django 4.0.4 on 2022-05-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='token',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
