# Generated by Django 4.0.4 on 2022-08-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_hospital_owner'),
        ('doctor', '0002_alter_doctor_hospital_to_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital_to_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
